<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domain\Access\Role;
use App\Domain\Crm\ConsentChannel;
use App\Domain\Crm\ConsentPurpose;
use App\Domain\Modules\Module;
use App\Models\Bay;
use App\Models\Branch;
use App\Models\BranchModule;
use App\Models\Consent;
use App\Models\Contact;
use App\Models\CustomerAccount;
use App\Models\Organization;
use App\Models\OrganizationModule;
use App\Models\Technician;
use App\Models\User;
use App\Tenancy\TenantManager;
use Brick\Money\Money;
use Carbon\CarbonImmutable;
use Database\Seeders\Demo\FleetSeed;
use Database\Seeders\Demo\PartsSeed;
use Database\Seeders\Demo\WorkOrderSeed;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use JsonException;
use RuntimeException;

/**
 * The demo tenant, from ../web's own demo data:
 *
 *  - database/seeders/data/demo-seed.json (../web/fixtures/seed, generated by
 *    ../web/scripts/emit-seed-json.ts): the provider becomes the organization,
 *    each fleet client a company customer account (Bayani Construction stays
 *    suspended), with its contact as the primary contact and its fleet
 *    contract carried over as granted service_records / service_reminders
 *    consent (channel `import`);
 *  - DEMO_USERS: the frontend's demo accounts (../web/lib/auth.ts, the same
 *    list the tenancy golden sweep covers), same emails, names, titles and
 *    roles, password `demo1234`;
 *  - two branches: MekanikoMoR-Biñan (repair_pms) and Samahuzai-Biñan
 *    (detailing + equipment), with ../web/lib/bays.ts and
 *    ../web/lib/technicians.ts in the repair branch. Both are VAT-registered
 *    and quote prices exclusive of VAT (VAT on top, as ../web bills);
 *  - the fleet (Demo\FleetSeed), then the work orders and approval settings
 *    (Demo\WorkOrderSeed), booked into the repair branch; then the vendors,
 *    each client's own spare parts and its purchase orders (Demo\PartsSeed).
 *
 * API-only additions, marked below: a branch manager and a cashier demo
 * account, and a small detailing floor at Samahuzai-Biñan.
 *
 * Runs in the named system context "demo seeder". Refuses to run in
 * production: these accounts share a published password.
 */
final class DemoSeeder extends Seeder
{
    public const string PASSWORD = 'demo1234';

    public const string REPAIR_BRANCH = 'mekanikomor-binan';

    public const string DETAILING_BRANCH = 'samahuzai-binan';

    /**
     * email, name, title, role, fleet client id (null = staff), branch pins.
     *
     * @var list<array{0: string, 1: string, 2: string, 3: Role, 4: string|null, 5: list<string>}>
     */
    public const array DEMO_USERS = [
        ['owner@mekanikomore.ph', 'Mike Manabat', 'Owner / Provider Admin', Role::ProviderAdmin, null, []],
        ['advisor@mekanikomore.ph', 'Divina Lacson', 'Service Advisor', Role::ServiceAdvisor, null, []],
        ['bay@mekanikomore.ph', 'Arnel Pascual', 'Provider Technician', Role::ProviderTechnician, null, []],
        ['donmiguel@mekanikomor.ph', 'Don Miguel', 'Fleet Manager', Role::FleetManager, 'fc-actimed', []],
        ['ops@mekanikomore.ph', 'Marisol Bautista', 'Operations Supervisor', Role::Operations, 'fc-actimed', []],
        ['tech@mekanikomore.ph', 'Arnel Pascual', 'Lead Technician', Role::Technician, 'fc-actimed', []],
        ['purchasing@mekanikomor.ph', 'Grace Villanueva', 'Purchasing Officer', Role::PurchasingOfficer, 'fc-actimed', []],
        ['viewer@mekanikomore.ph', 'Camille Ortega', 'Authorised Viewer', Role::Viewer, 'fc-actimed', []],
        ['fleet@northwind.ph', 'Ruben Salcedo', 'Fleet Manager', Role::FleetManager, 'fc-northwind', []],
        ['operations@sagrada.ph', 'Imelda Cortez', 'Operations Director', Role::FleetManager, 'fc-sagrada', []],
        ['yard@bayanicon.ph', 'Andres Malolos', 'Yard Manager (suspended account)', Role::FleetManager, 'fc-bayani', []],
        // API-only demo accounts for the two new staff roles.
        ['manager.samahuzai@mekanikomore.ph', 'Liza Samonte', 'Branch Manager, Samahuzai-Biñan', Role::BranchManager, null, [self::DETAILING_BRANCH]],
        ['cashier@mekanikomore.ph', 'Paolo Reyes', 'Front Counter Cashier', Role::Cashier, null, [self::REPAIR_BRANCH]],
    ];

    /** ../web/lib/bays.ts */
    private const array REPAIR_BAYS = [
        ['bay-1', 'Bay 1', 'General service'],
        ['bay-2', 'Bay 2', 'General service'],
        ['bay-3', 'Bay 3', 'Heavy & drivetrain'],
        ['bay-4', 'Bay 4', 'Tyres & alignment'],
        ['bay-5', 'Bay 5', 'Diagnostics & electrical'],
    ];

    /** ../web/lib/technicians.ts: name, specialty, home bay. */
    private const array REPAIR_TECHNICIANS = [
        ['Arnel Pascual', 'engine', 'bay-1'],
        ['Jomar Dizon', 'brakes', 'bay-2'],
        ['Kristine Abad', 'drivetrain', 'bay-3'],
        ['Lito Sarmiento', 'tires', 'bay-4'],
        ['Michelle Garcia', 'electrical', 'bay-5'],
        ['Renato Ilagan', 'general', 'bay-1'],
    ];

    /** API-only: a detailing floor, so the detailing branch is not empty. */
    private const array DETAILING_BAYS = [['detail-1', 'Detail Bay 1', 'Wash & decon'], ['detail-2', 'Detail Bay 2', 'Paint correction & coating']];

    private const array DETAILING_TECHNICIANS = [['Jessa Manalo', 'paint correction', 'detail-2'], ['Rico Dimaculangan', 'interior', 'detail-1']];

    /**
     * Source id (provider, fleet client, branch slug, bay key, user email) →
     * the ULID this run created. Tests map golden fixture ids through it.
     *
     * @var array<string, string>
     */
    public array $ids = [];

    public function run(): void
    {
        if (app()->isProduction()) {
            throw new RuntimeException('DemoSeeder creates accounts with a published password; it never runs in production.');
        }

        app(TenantManager::class)->system('demo seeder', fn () => DB::transaction(fn () => $this->seed()));
    }

    private function seed(): void
    {
        $data = self::data();
        $state = self::map($data['state'] ?? null);
        $provider = self::map(self::list($state['providers'] ?? null)[0] ?? null);
        $since = CarbonImmutable::parse(self::str($provider['createdAt'] ?? null), 'Asia/Manila')->utc();

        $organization = new Organization;
        $organization->forceFill([
            'name' => 'MekanikoMoR',
            'slug' => self::str($provider['slug'] ?? null),
            'support_email' => $provider['supportEmail'] ?? null,
            'brand_color' => $provider['brandColor'] ?? null,
            'logo_url' => $provider['logoUrl'] ?? null,
            'status' => 'active',
            'created_at' => $since,
        ])->save();
        $this->ids[self::str($provider['id'] ?? null)] = $organization->id;

        $repair = $this->branch($organization, 'MekanikoMoR-Biñan', self::REPAIR_BRANCH, null, [Module::RepairPms]);
        $detailing = $this->branch($organization, 'Samahuzai-Biñan', self::DETAILING_BRANCH, 'Samahuzai', [Module::Detailing, Module::Equipment]);

        foreach ([Module::RepairPms, Module::Detailing, Module::Equipment] as $module) {
            (new OrganizationModule)->forceFill(['organization_id' => $organization->id, 'module' => $module, 'enabled' => true])->save();
        }

        foreach (self::list($state['fleetClients'] ?? null) as $client) {
            $this->account($organization, self::map($client));
        }

        $this->floor($organization, $repair, self::REPAIR_BAYS, self::REPAIR_TECHNICIANS, 'mechanic');
        $this->floor($organization, $detailing, self::DETAILING_BAYS, self::DETAILING_TECHNICIANS, 'detailer');

        $password = Hash::make(self::PASSWORD);
        foreach (self::DEMO_USERS as [$email, $name, $title, $role, $clientId, $pins]) {
            $user = new User;
            $user->forceFill([
                'organization_id' => $organization->id,
                'side' => $role->side(),
                'role' => $role,
                'customer_account_id' => $clientId === null ? null : $this->ids[$clientId],
                'name' => $name,
                'title' => $title,
                'email' => $email,
                'password' => $password,
                'email_verified_at' => $since,
                'status' => User::ACTIVE,
            ])->save();
            $user->branches()->attach(array_fill_keys(
                array_map(fn (string $slug): string => $this->ids[$slug], $pins),
                ['organization_id' => $organization->id],
            ));
            $this->ids[$email] = $user->id;
        }

        FleetSeed::run($organization->id, $data, $this->ids);
        WorkOrderSeed::run($organization->id, $repair->id, $data, $this->ids);
        PartsSeed::run($organization->id, $data, $this->ids);
    }

    /**
     * @param  list<Module>  $modules
     */
    private function branch(Organization $organization, string $name, string $slug, ?string $brandName, array $modules): Branch
    {
        $branch = new Branch;
        $branch->forceFill([
            'organization_id' => $organization->id,
            'name' => $name,
            'slug' => $slug,
            'brand_name' => $brandName,
            'address' => 'Biñan, Laguna',
            'timezone' => 'Asia/Manila',
            'is_vat_registered' => true,
            // VAT on top of quoted prices, as ../web bills. Inclusive pricing arrives with invoicing.
            'prices_include_vat' => false,
            'status' => 'active',
        ])->save();
        $this->ids[$slug] = $branch->id;

        foreach ($modules as $module) {
            (new BranchModule)->forceFill([
                'organization_id' => $organization->id,
                'branch_id' => $branch->id,
                'module' => $module,
                'enabled' => true,
            ])->save();
        }

        return $branch;
    }

    /**
     * @param  array<string, mixed>  $client
     */
    private function account(Organization $organization, array $client): void
    {
        $since = CarbonImmutable::parse(self::str($client['createdAt'] ?? null), 'Asia/Manila')->utc();

        $account = new CustomerAccount;
        $account->forceFill([
            'organization_id' => $organization->id,
            'account_type' => CustomerAccount::COMPANY,
            'display_name' => self::str($client['name'] ?? null),
            'registered_name' => self::str($client['name'] ?? null),
            'contact_name' => $client['contactName'] ?? null,
            'contact_email' => $client['contactEmail'] ?? null,
            'payment_terms_days' => $client['paymentTermsDays'] ?? 0,
            'approval_threshold_overrides' => self::overrides($client['approvalThresholdOverrides'] ?? null),
            'tags' => ['fleet'],
            'source' => 'fleet_contract',
            'notes' => 'Contract: '.self::str($client['contractTerms'] ?? null),
            'logo_url' => $client['logoUrl'] ?? null,
            'brand_color' => $client['brandColor'] ?? null,
            'status' => self::str($client['status'] ?? null),
            'created_at' => $since,
        ])->save();
        $this->ids[self::str($client['id'] ?? null)] = $account->id;

        if (is_string($client['contactName'] ?? null)) {
            (new Contact)->forceFill([
                'organization_id' => $organization->id,
                'customer_account_id' => $account->id,
                'name' => $client['contactName'],
                'role' => 'Fleet contact',
                'email' => $client['contactEmail'] ?? null,
                'is_primary' => true,
                'receives_invoices' => true,
                'receives_reminders' => true,
            ])->save();
        }

        foreach ([ConsentPurpose::ServiceRecords, ConsentPurpose::ServiceReminders] as $purpose) {
            (new Consent)->forceFill([
                'organization_id' => $organization->id,
                'customer_account_id' => $account->id,
                'purpose' => $purpose,
                'granted' => true,
                'channel' => ConsentChannel::Import,
                'captured_at' => $since,
                'captured_by' => null,
                'evidence' => 'Carried over from the fleet service contract: '.self::str($client['contractTerms'] ?? null),
            ])->save();
        }
    }

    /**
     * @param  list<array{0: string, 1: string, 2: string}>  $bays
     * @param  list<array{0: string, 1: string, 2: string}>  $technicians
     */
    private function floor(Organization $organization, Branch $branch, array $bays, array $technicians, string $skill): void
    {
        foreach ($bays as [$key, $name, $focus]) {
            $bay = new Bay;
            $bay->forceFill([
                'organization_id' => $organization->id,
                'branch_id' => $branch->id,
                'name' => $name,
                'focus' => $focus,
                'capacity_hours_per_day' => '9',
            ])->save();
            $this->ids['bay:'.$key] = $bay->id;
        }

        foreach ($technicians as [$name, $specialty, $homeBay]) {
            (new Technician)->forceFill([
                'organization_id' => $organization->id,
                'branch_id' => $branch->id,
                'name' => $name,
                'skill_tags' => [$skill],
                'specialty' => $specialty,
                'home_bay_id' => $this->ids['bay:'.$homeBay],
            ])->save();
        }
    }

    /**
     * The frontend's peso-valued, camelCase override keys → the API's
     * snake_case keys with money in centavos. Null stays null (inherit).
     *
     * @return array<string, int|string>|null
     */
    private static function overrides(mixed $overrides): ?array
    {
        if (! is_array($overrides)) {
            return null;
        }

        $money = ['autoApproveUnder' => 'auto_approve_under_cents', 'opsApprovalUnder' => 'ops_approval_under_cents', 'monthlyBudget' => 'monthly_budget_cents'];
        $plain = ['slaHours' => 'sla_hours', 'varianceThresholdPct' => 'variance_threshold_pct', 'defaultPartsSource' => 'default_parts_source'];

        $converted = [];
        foreach ($overrides as $key => $value) {
            if (isset($money[$key]) && (is_int($value) || is_float($value))) {
                $converted[$money[$key]] = Money::of((string) $value, 'PHP')->getMinorAmount()->toInt();
            } elseif (isset($plain[$key]) && (is_int($value) || is_string($value))) {
                $converted[$plain[$key]] = $value;
            } else {
                throw new RuntimeException("Unmapped approval override [{$key}] in the demo seed.");
            }
        }

        return $converted;
    }

    /**
     * @return array<string, mixed>
     *
     * @throws JsonException
     */
    public static function data(): array
    {
        $json = file_get_contents(__DIR__.'/data/demo-seed.json');
        if ($json === false) {
            throw new RuntimeException('database/seeders/data/demo-seed.json is missing.');
        }

        return self::map(json_decode($json, true, flags: JSON_THROW_ON_ERROR));
    }

    /**
     * @return array<string, mixed>
     */
    private static function map(mixed $value): array
    {
        if (! is_array($value)) {
            throw new RuntimeException('Unexpected demo seed shape.');
        }

        /** @var array<string, mixed> $value */
        return $value;
    }

    /**
     * @return list<mixed>
     */
    private static function list(mixed $value): array
    {
        return is_array($value) ? array_values($value) : [];
    }

    private static function str(mixed $value): string
    {
        if (! is_string($value)) {
            throw new RuntimeException('Unexpected demo seed value.');
        }

        return $value;
    }
}
